name: Build and deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      # Define tool versions
      GO_VERSION: 1.25.5
      HUGO_VERSION: 0.164.0
      TZ: Asia/Taipei
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
          # fetch-depth: 0
          lfs: false

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Install dependencies
        run: pnpm install --prod --frozen-lockfile --ignore-scripts

      - name: Build
        run: hugo build --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/" && pnpm pagefind --site public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          include-hidden-files: false
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
